### ISSUE TITLE
Script incompatibility (see comment)

### ISSUE THREAD

**Issue by SirGouki** [smolgumball/bb-vue#10]
The script at https://steamcommunity.com/sharedfiles/filedetails/?id=2689036632 crashes the dashboard script with an error along the lines of "unable to read from slice: slice is undefined" with a stack pointing at the orchestrator.  Will edit this with a screen shot of the error happening in a few minutes.

![image](https://user-images.githubusercontent.com/11664236/147899405-5350ba71-d72a-48cb-b455-8865ea9cc669.png)

In order to run the dashboard again, I have to do a reload + kill all scripts.  I have tested a different script that spawns the same scripts in a similar way with no problems.  There are still some differences I'm trying to narrow down, but I can confirm it has nothing to do with executing other scripts inside of a script while the dashboard is running.  I have some suspicions I'm still testing and will either edit this or comment it in when I find anything else that causes the crash.

Edit:
I have found the source of the error.  The linked script contains the following code at the top:

```js
//additional function, needed to merge arrays.
Array.prototype.unique = function() 
{
    var a = this.concat();
    for(var i=0; i<a.length; ++i) 
    {
        for(var j=i+1; j<a.length; ++j) 
        {
            if(a[i] === a[j])
                a.splice(j--, 1);
        }
    }
    return a;
};
```

adding this code to my otherwise working script caused the exact same crash as the one pictured.

This can be as minor as crashing vue, or as major as causing memory related error when doing reload + kill all.

**Comment by SirGouki** [comment]
I have changed my version of the script that was triggering this error and contacted the author of the original to let them know via the comments on the linked steam page.  As I don't know enough about how vue works vs javascript as a whole, I have no idea whether this is being caused by vue itself, or by the code for the dashboard app.

**Comment by smolgumball** [comment]
Heya @SirGouki, I sadly can't really do much to support this particular case. Any scripts that attempt to patch the prototypes of built-in JavaScript functions / types are going to cause a wild ruckus. This is because Vue expects integrity of existing JS data types.

If you're looking for an alternative to prototype patching, and specifically need an array uniqueness solution, I'd recommend using the built-in instance of Lodash that exists in the game. You can access it via `globalThis._`, or through the helper method packaged with bb-vue:

```js
import { lodash } from '/bitburner-vue/lib/.js

let arr = [1, 2, 2, 3]
arr = lodash.uniq(arr)
console.log(arr) // arr[1, 2, 3]
```

**Comment by SirGouki** [comment]
I figured as much, which is why I replaced the code.  I had no reason to rely on messing with the prototypes (other than a secret, which did not mess with Vue at all), just figured I'd point it out incase it *could* have been fixed.  Would be a good thing to notify users of:  "Do not combine this script with scripts that modify prototypes of Javascript built-ins" or some such.
