### ISSUE TITLE
Tutorial doesn't seem to be working

### ISSUE THREAD

**Issue by wchevalier** [smolgumball/bb-vue#12]
Followed steps in the readme but I seem to be having an issue:
![image](https://user-images.githubusercontent.com/97134273/149650833-f7d07fb5-c740-4805-8065-b255d795bef8.png)

Got the same result in both Steam and Chrome versions of the game
Here are the steps and console outputs to reproduce:

```
[home ~/]> nano bbv-inst.js
[home ~/]> run /bbv-inst.js dev
Running script with 1 thread(s), pid 35417 and args: ["dev"].
bbv-inst.js: Installed: /bb-vue/AppFactory.js [1/37]
bbv-inst.js: Installed: /bb-vue/ComponentManager.js [2/37]
bbv-inst.js: Installed: /bb-vue/components/AppRoot.js [3/37]
bbv-inst.js: Installed: /bb-vue/components/AppRoot.Styles.js [4/37]
bbv-inst.js: Installed: /bb-vue/components/AppTray.js [5/37]
bbv-inst.js: Installed: /bb-vue/components/AppTrayGroup.js [6/37]
bbv-inst.js: Installed: /bb-vue/components/Button.js [7/37]
bbv-inst.js: Installed: /bb-vue/components/concerns/useDraggableWin.js [8/37]
bbv-inst.js: Installed: /bb-vue/components/internal/ConsumerRoot.js [9/37]
bbv-inst.js: Installed: /bb-vue/components/internal/CssManager.js [10/37]
bbv-inst.js: Installed: /bb-vue/components/internal/ScriptX.js [11/37]
bbv-inst.js: Installed: /bb-vue/components/JsonDisplay.js [12/37]
bbv-inst.js: Installed: /bb-vue/components/Tabs.js [13/37]
bbv-inst.js: Installed: /bb-vue/components/Win.js [14/37]
bbv-inst.js: Installed: /bb-vue/components/WinManager.js [15/37]
bbv-inst.js: Installed: /bb-vue/components/_resources.js [16/37]
bbv-inst.js: Installed: /bb-vue/examples/0-getting-started.js [17/37]
bbv-inst.js: Installed: /bb-vue/examples/1-the-app-tray.js [18/37]
bbv-inst.js: Installed: /bb-vue/examples/2-events-and-communication.js [19/37]
bbv-inst.js: Installed: /bb-vue/examples/3-connecting-with-scripts.js [20/37]
bbv-inst.js: Installed: /bb-vue/examples/4-complex-and-fun.js [21/37]
bbv-inst.js: Installed: /bb-vue/lib.js [22/37]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-collector.js [23/37]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-lib.js [24/37]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-ui.js [25/37]
bbv-inst.js: Installed: /bb-vue/misc-examples/svgchart-builder.js [26/37]
bbv-inst.js: Installed: /bb-vue/misc-examples/svgchart-ui.js [27/37]
bbv-inst.js: Installed: /bb-vue/MittLoader.js [28/37]
bbv-inst.js: Installed: /bb-vue/new-examples/0-getting-started.js [29/37]
bbv-inst.js: Installed: /bb-vue/new-examples/1-adding-components.js [30/37]
bbv-inst.js: Installed: /bb-vue/new-examples/2-writing-styles-scss.js [31/37]
bbv-inst.js: Installed: /bb-vue/new-examples/3-controlling-your-app.js [32/37]
bbv-inst.js: Installed: /bb-vue/new-examples/4-sending-data-from-scripts.js [33/37]
bbv-inst.js: Installed: /bb-vue/new-examples/5-demo-app.js [34/37]
bbv-inst.js: Installed: /bb-vue/package.txt [35/37]
bbv-inst.js: Installed: /bb-vue/SassLoader.js [36/37]
bbv-inst.js: Installed: /bb-vue/VueLoader.js [37/37]
bbv-inst.js: Install complete! 🎉
Run the following in your home terminal for an example that uses bb-vue:
run /bb-vue/examples/0-getting-started.js

[home ~/]> run /bb-vue/examples/0-getting-started.js
Running script with 1 thread(s), pid 35460 and args: [].
/bb-vue/examples/0-getting-started.js: Error: rootApp cannot be located, or issue mounting consumer appDef:
{}
```

**Comment by smolgumball** [comment]
heya @wchevalier, thanks for the report! sadly i'm having trouble reproducing

can you try popping open your devtools in Chrome (F12) and repeating the process? 
specifically, check the Network tab and the Console tabs for any additional details.

if you're willing, it might be worth trying again with a freshly wiped game on the web version (backup first if you play there primarily!) - you can do this through Options -> Delete Game

lastly, I'd ask what platform your on. the font rendering in your screenshot seems to suggest linux, but I could be making an assumption there :)

**Comment by wchevalier** [comment]
Sorry I just saw you had replied. The error has changed but it is the same in both chrome and steam. I primarily play on steam, but if I run into issues I hop onto chrome and use the web version. 

For the below test I used chrome incognito so no save file at all to start with. I have attached my save file from this test.
Bitburner v1.4.0 (1e126d40)
[home ~/]> nano bbv-inst.js
[home ~/]> nano bbv-inst.js
[home ~/]> run /bbv-inst.js dev
Running script with 1 thread(s), pid 1 and args: ["dev"].
bbv-inst.js: Installed: /bb-vue/AppFactory.js [1/39]
bbv-inst.js: Installed: /bb-vue/ComponentManager.js [2/39]
bbv-inst.js: Installed: /bb-vue/components/Button.js [3/39]
bbv-inst.js: Installed: /bb-vue/components/concerns/useDraggableWin.js [4/39]
bbv-inst.js: Installed: /bb-vue/components/internal/AppRoot.js [5/39]
bbv-inst.js: Installed: /bb-vue/components/internal/AppRoot.Styles.js [6/39]
bbv-inst.js: Installed: /bb-vue/components/internal/AppTray.js [7/39]
bbv-inst.js: Installed: /bb-vue/components/internal/AppTrayGroup.js [8/39]
bbv-inst.js: Installed: /bb-vue/components/internal/ConsumerRoot.js [9/39]
bbv-inst.js: Installed: /bb-vue/components/internal/CssManager.js [10/39]
bbv-inst.js: Installed: /bb-vue/components/internal/ScriptX.js [11/39]
bbv-inst.js: Installed: /bb-vue/components/internal/Win.js [12/39]
bbv-inst.js: Installed: /bb-vue/components/internal/WinManager.js [13/39]
bbv-inst.js: Installed: /bb-vue/components/internal/_resources.js [14/39]
bbv-inst.js: Installed: /bb-vue/components/JsonDisplay.js [15/39]
bbv-inst.js: Installed: /bb-vue/components/LogDisplay.js [16/39]
bbv-inst.js: Installed: /bb-vue/components/ObjectDisplay.js [17/39]
bbv-inst.js: Installed: /bb-vue/components/Tabs.js [18/39]
bbv-inst.js: Installed: /bb-vue/examples/0-getting-started.js [19/39]
bbv-inst.js: Installed: /bb-vue/examples/1-the-app-tray.js [20/39]
bbv-inst.js: Installed: /bb-vue/examples/2-events-and-communication.js [21/39]
bbv-inst.js: Installed: /bb-vue/examples/3-connecting-with-scripts.js [22/39]
bbv-inst.js: Installed: /bb-vue/examples/4-complex-and-fun.js [23/39]
bbv-inst.js: Installed: /bb-vue/lib.js [24/39]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-collector.js [25/39]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-lib.js [26/39]
bbv-inst.js: Installed: /bb-vue/misc-examples/asciichart-ui.js [27/39]
bbv-inst.js: Installed: /bb-vue/misc-examples/svgchart-builder.js [28/39]
bbv-inst.js: Installed: /bb-vue/misc-examples/svgchart-ui.js [29/39]
bbv-inst.js: Installed: /bb-vue/MittLoader.js [30/39]
bbv-inst.js: Installed: /bb-vue/new-examples/0-getting-started.js [31/39]
bbv-inst.js: Installed: /bb-vue/new-examples/1-adding-components.js [32/39]
bbv-inst.js: Installed: /bb-vue/new-examples/2-writing-styles-scss.js [33/39]
bbv-inst.js: Installed: /bb-vue/new-examples/3-controlling-your-app.js [34/39]
bbv-inst.js: Installed: /bb-vue/new-examples/4-sending-data-from-scripts.js [35/39]
bbv-inst.js: Installed: /bb-vue/new-examples/5-demo-app.js [36/39]
bbv-inst.js: Installed: /bb-vue/package.txt [37/39]
bbv-inst.js: Installed: /bb-vue/SassLoader.js [38/39]
bbv-inst.js: Installed: /bb-vue/VueLoader.js [39/39]
bbv-inst.js: Install complete! 🎉
Run the following in your home terminal for an example that uses bb-vue:
run /bb-vue/examples/0-getting-started.js

[home ~/]> run /bb-vue/examples/0-getting-started.js
Running script with 1 thread(s), pid 2 and args: [].
[home ~/]> 



RUNTIME ERROR
/bb-vue/examples/0-getting-started.js@home
[bitburnerSave_1642563636_BN1x0.json.txt](https://github.com/smolgumball/bb-vue/files/7893970/bitburnerSave_1642563636_BN1x0.json.txt)


Failed to resolve module specifier "/nuburn/lib/util.js". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/nuburn/lib/util.js". Invalid relative url or base scheme isn't hierarchical.

**Comment by smolgumball** [comment]
Heya @wchevalier, glad you commented here. 

Looks like we made it a bit further than last time, but I seem to have botched the dependencies between `bb-vue` and `nuburn` in the mean time. 

Go ahead and try a fresh install, I just pushed an update: 25e0bec

**Comment by wchevalier** [comment]
Partially working... not in my game but on a clean incognito chrome window it installed and ran .0-getting-started.js . Now I need to figure out what is different between chrome and steam lol :) 

Steam version is giving the original error of 
Running script with 1 thread(s), pid 35460 and args: [].
/bb-vue/examples/0-getting-started.js: Error: rootApp cannot be located, or issue mounting consumer appDef:
{}

I play on windows 8.1 - Steam

**Comment by smolgumball** [comment]
@wchevalier Can you try **backing up your Steam save first**, and then pressing "Delete Game" in options menu, re-installing bb-vue and letting me know if you get the same error? Thinking you may have a stale install in your Steam save that's causing issues.
