### ISSUE TITLE
nuburn script dependancies to bb-vue location...

### ISSUE THREAD

**Issue by corto-72** [smolgumball/bb-vue#13]
If you use the opportunity to use prefix directory for bb-vue install, dependancies to bb-vue files are broken in nuburn scripts

**Comment by smolgumball** [comment]
Thanks for the bug report, @corto-72! I'll get something whipped up to fix that ASAP.

**Comment by smolgumball** [comment]
Heya @corto-72, this should be fixed! Go ahead and grab the latest installers from `install.js` and `installNuburn.js` and give them a go. Make sure you provide your `bb-vue` path in the `nuburn` installer.

**Comment by corto-72** [comment]
All good now ;) !!!!
