### ISSUE TITLE
Suggestion - Repl.js

### ISSUE THREAD

**Issue by corto-72** [smolgumball/bb-vue#14]
I think it would be good to add a kill button for infinite loop scripts rather than having to shutdown the window - it would allow to stop / update code  and then rerun it straight away

**Comment by smolgumball** [comment]
Heya @corto-72, this should be supported as-is:
![image](https://user-images.githubusercontent.com/53015256/150393450-71a38bc1-4fc3-474e-be26-64a3553e5e63.png)

**Comment by corto-72** [comment]
I did not have the button... so I followed your advice on the other bug  - clean install did not work, I tried the browser version which worked... but also told me a new version of the game was out  :)
after I updated on steam, all good!!!
