### ISSUE TITLE
nuburn - reboot of one instance remove the other one

### ISSUE THREAD

**Issue by corto-72** [smolgumball/bb-vue#15]
I started both start.js and then repl.js. I then clicked on the reboot button for REPL. REPL restarted, but the other instances windows disappeared whilst the script was still running in the background...

Not certain this is easily fixable...

**Comment by smolgumball** [comment]
@corto-72 I'm actually not able to reproduce this one. The shutdown and restart buttons for both start.js and repl.js should result in separate restarts. One thing you might want to do is clean out the nuburn + bb-vue installs you currently have and do a fresh reinstall just to be sure all the most up-to-date files are in place.

If that doesn't fix the issue, I wonder if you could try reproducing in a neutral environment like the [browser version of the game](https://danielyxie.github.io/bitburner/) with a freshly reset savegame (e.g. Options -> Delete Save). Make sure to backup your save if you play through the browser primarily.

**Comment by corto-72** [comment]
as per other comment, after game update all good... sorry about this !!!

**Comment by smolgumball** [comment]
No worries, thanks @corto-72!
